# Generated by Django 6.0.3 on 2026-03-25 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupidea',
            name='market_score',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth0_id',
        ),
        migrations.AddField(
            model_name='startupidea',
            name='challenges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='competition_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='investment_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='key_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='market_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='problem_solved',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='revenue_streams',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='startupidea',
            name='target_audience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='idea',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.startupidea'),
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='business_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='viability_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('idea_description', models.TextField(blank=True, null=True)),
                ('region', models.CharField(default='Bangladesh', max_length=100)),
                ('focus_area', models.CharField(default='comprehensive', max_length=50)),
                ('founded_year', models.IntegerField(blank=True, null=True)),
                ('headquarters', models.CharField(blank=True, max_length=200, null=True)),
                ('market_presence', models.CharField(blank=True, max_length=200, null=True)),
                ('funding_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('total_funding', models.CharField(blank=True, max_length=100, null=True)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('opportunities', models.JSONField(blank=True, default=list)),
                ('threats', models.JSONField(blank=True, default=list)),
                ('market_share', models.CharField(blank=True, max_length=50, null=True)),
                ('key_features', models.JSONField(blank=True, default=list)),
                ('target_customers', models.JSONField(blank=True, default=list)),
                ('pricing_model', models.CharField(blank=True, max_length=100, null=True)),
                ('review_sentiment', models.TextField(blank=True, null=True)),
                ('threat_score', models.FloatField(blank=True, default=0, null=True)),
                ('market_leader_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competitors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='competitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.competitor'),
        ),
        migrations.CreateModel(
            name='MarketAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('industry', models.CharField(max_length=100)),
                ('region', models.CharField(default='Bangladesh', max_length=100)),
                ('compare_with', models.CharField(blank=True, max_length=100, null=True)),
                ('market_size_tam', models.CharField(blank=True, max_length=100, null=True)),
                ('market_size_sam', models.CharField(blank=True, max_length=100, null=True)),
                ('market_size_som', models.CharField(blank=True, max_length=100, null=True)),
                ('growth_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('key_trends', models.JSONField(blank=True, default=list)),
                ('customer_segments', models.JSONField(blank=True, default=list)),
                ('market_drivers', models.JSONField(blank=True, default=list)),
                ('market_barriers', models.JSONField(blank=True, default=list)),
                ('regulatory_factors', models.JSONField(blank=True, default=list)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('market_maturity', models.CharField(blank=True, max_length=50, null=True)),
                ('competition_intensity', models.CharField(blank=True, max_length=50, null=True)),
                ('opportunity_score', models.IntegerField(blank=True, default=0, null=True)),
                ('entry_strategies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='market_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.marketanalysis'),
        ),
        migrations.CreateModel(
            name='SkillsGapAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skills', models.TextField(blank=True, null=True)),
                ('startup_type', models.CharField(default='SaaS Platform', max_length=100)),
                ('experience_level', models.CharField(default='1-2 years', max_length=50)),
                ('required_skills', models.JSONField(blank=True, default=list)),
                ('current_skills', models.JSONField(blank=True, default=list)),
                ('gap_skills', models.JSONField(blank=True, default=list)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('skill_areas', models.JSONField(blank=True, default=list)),
                ('readiness_score', models.IntegerField(blank=True, default=0, null=True)),
                ('top_gaps', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('learning_path', models.JSONField(blank=True, default=list)),
                ('timeline_projection', models.JSONField(blank=True, default=list)),
                ('recommended_roles', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills_analyses', to='users.startupidea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skills_gap_analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='skills_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.skillsgapanalysis'),
        ),
    ]
