# Generated by Django 6.0.3 on 2026-03-26 02:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_remove_startupidea_market_score_remove_user_auth0_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='analysisreport',
            old_name='competitor_landscape',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='customer_insights',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='executive_summary',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='export_formats',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='financial_forecast',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='market_size',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='pdf_report',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='pitch_deck',
        ),
        migrations.RemoveField(
            model_name='analysisreport',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='competitor_analysis',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='feasibility_score',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='financial_projections',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='innovation_score',
        ),
        migrations.RemoveField(
            model_name='startupidea',
            name='risk_assessment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_status',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_agent',
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='pdf_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='report_type',
            field=models.CharField(default='analysis', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='title',
            field=models.CharField(default='Default Report', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysisreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.competitor'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.startupidea'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='market_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.marketanalysis'),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='skills_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.skillsgapanalysis'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='funding_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='market_presence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='pricing_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='review_sentiment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='competition_intensity',
            field=models.CharField(blank=True, default='Medium', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='market_maturity',
            field=models.CharField(blank=True, default='Emerging', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='marketanalysis',
            name='opportunity_score',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name='skillsgapanalysis',
            name='startup_idea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.startupidea'),
        ),
        migrations.AlterField(
            model_name='startupidea',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='users_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
